### ISSUE TITLE
When Xocitl turns off, rather than making the ReMarkable turn off, it goes back to Draft

### ISSUE THREAD

**Issue by Qqwy** [dixonary/draft-reMarkable#4] opened 2018-10-05 11:59 UTC
When Xochitl is first in sleep mode, and then turns off, the ReMarkable does not turn off, but goes back to the Draft Launcher.

This has a big implication for battery life, since it is then slowly draining.

I'm not sure there is an easy way to check if Xochitl wanted to turn the system off, but maybe it is possible to check the same configuration file from Draft to see if more than X minutes have passed, and if so, execute the shutdown handler?

**Comment by dixonary** [comment] 2018-10-05 15:43
Hey Qqwy,

Thanks for informing me of this - it's not something I had previously considered. 

It would be possible to tell draft to automatically shut down rather than returning to the menu, in the case where over X minutes has passed. I'm not sure if that would have a negative effect on the quality of life for people using other applications. 

So currently, options are:

* Automatically shutdown if the child application was open for a long enough time
* Find out why the rM would *normally* shut down directly when xochitl closes (possibly something to do with the systemctl service file?)
* Find another, better way of forcing Draft to shutdown cleanly when xochitl/other child apps want it to.

I don't currently have the time to make this enhancement but I will definitely consider pull requests for anyone else who does!

**Comment by Evidlo** [comment] 2019-01-04 02:05
Is this a bug or a feature?  Is there any other way to exit xochitl and return to Draft, without shutting off the device?

*edit* ignore this.  I wasn't aware of 'button-capture-reMarkable'

**Comment by dixonary** [comment] 2019-01-05 14:23
It's working as intended, but I agree that it would be nice if there was a way to force Xochitl to "shut down" fully rather than returning to Draft every time.

If you wanted to, you could change out the command in the configuration file from `/usr/bin/xochitl` to `/usr/bin/xochitl; shutdown` or however the "shutdown" program is invoked on rM. That would shut the machine down fully once xochitl ends for any reason. 

As you have mentioned, `button-capture-reMarkable` is a decent way of making this work without changing configuration!

**Comment by Qqwy** [comment] 2019-01-29 12:48
@dixonary I have tried altering the configuration, but this does not seem to do anything. ('shutdown' is the correct command to shut down the ReMarkable, but `/usr/bin/xochitl; shutdown` will still return to Draft rather than properly shutting down everything. )


EDIT: `/usr/bin/xochitl; shutdown now` works properly, however :sweat_smile: .

**Comment by dixonary** [comment] 2019-01-29 12:52
~~That is very interesting. I would definitely expect that to shut down the system.~~

~~I will take a look at the next opportunity but that may not be for a little while. If anyone else would take a look I'd be grateful!~~

Edit: glad you got it working! Sorry, didn't know the correct syntax for shutdown.

**Comment by dixonary** [comment] 2019-08-04 17:00
Closing for now, as this can be worked around without changing `draft` directly (see above).

**Closed as completed by dixonary** 2019-08-04 17:00 UTC
Labels: bug
